# frozen_string_literal: true

ruby '3.2.2'

source 'https://rubygems.org'

group :test do
  gem 'rspec'
end
gem 'multi_json'
gem 'rack-session'
gem 'sinatra-flash'
gem 'webrick'
# github 'sinatra/sinatra' do
gem 'sinatra'
gem 'sinatra-contrib'
# end

gem 'bcrypt'
gem 'rack-test'
gem 'rake'
gem 'rubocop', require: false
gem 'simplecov'
gem 'sinatra-activerecord'
gem 'sqlite3'
