ruby '3.2.2'

source 'https://rubygems.org'

gem 'multi_json'
gem 'rack-session'
gem 'sinatra-flash'
gem 'webrick'
# github 'sinatra/sinatra' do
gem 'sinatra'
gem 'sinatra-contrib'
# end

gem 'rake'
gem 'sinatra-activerecord'
gem 'sqlite3'
